project:
  type: website
  output-dir: docs

website:
  title: "Fede's Hub"
  favicon: media/fdl-high-resolution-logo-transparent.png
  navbar:
    right:
      - href: about.qmd
        text: About Me
      - text: Projects
        menu: 
          - href: academicprojects/gpr4golf.qmd
            text: Gaussian Process Regression For Golf
          - href: academicprojects/timeCourse.qmd
            text: Validating sicegar
      - text: Off My Laptop
        menu:
          - href: golf/index.qmd
            text: Overview
      - href: smallprojs/index.qmd
        text: Byte-Sized Projects
    title: Fede on Par
    logo: media/fdl-high-resolution-logo-transparent.png
    logo-alt: "FDL logo"
  page-footer:
    background: $denim
    left: Copyright 2025, Federica Domecq
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://fedegudom47.github.io/){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: 
    - flatly
    - styles.scss
    toc: true
    page-layout: full
    includes:
      in-header: |
          <link rel="preconnect" href="https://rsms.me/">
          <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

editor: source

