---
title: ""
format: html
---
## Hi There! 👋

My name is **Federica**, and I am a senior at **Pomona College**, double majoring in **Mathematics & Computer Science**. Originally from **Madrid, Spain 🇪🇸**, I moved to the U.S. to pursue new opportunities and currently live in **Claremont, California**.

Over the last four years, I have come to love using data to turn messy problems into clear decisions. My work sits at the intersection of **statistical modeling, optimisation, machine learning, and data visualisation** - I enjoy everything from building predictive models to crafting visual stories that make results accessible.

### Lengthy Projects
I have spent the past two summers in [Pomona College](https://www.pomona.edu/) doing some really exciting work alongside some of my favourite Professors: 

- **Summer '25, Simulating Golf Strategy using Gaussian Process Regression** During this project we developed a novel data-driven framework to help golfers make better strategic decisions on the course. We modeled golf as a sequential decision-making problem under uncertainty, creating a tool that offers personalized, data-backed recommendations. Using 2D Gaussian Process Regression (GPR), we built a model that assesses the scoring impact of different club and aimpoint combinations. The framework can be tailored to an individual golfer's tendencies (recorded on Trackman data) and needs, alongside the specific golf course layout, and can be adjusted to either minimise expected strokes (the best score on average) or maximise birdie odds (for high-stakes situations). The work establishes a scalable foundation for a future decision-support tool that provides dynamic, adaptive strategy in real-time based on shot outcomes. I produced this work alongside [Professor Gabriel Chandler](https://www.pomona.edu/directory/people/gabriel-chandler). Find out more about this work [here](academicprojects/gpr4golf.qmd).
- **Summer '24, Evaluating the Reliability of Sicegar for Timing Analysis of RpoS-Dependent Gene Expression** We used a simulation-based approach to evaluate the `sicegar` R package, a tool used by biologists to analyse gene expression data. The project focused on assessing whether the package could reliably detect sigmoidal and double-sigmoidal curves and accurately estimate their onset times - the points where gene expression significantly increases and therefore is activated. By generating synthetic data with known parameters and then introducing noise, we tested the software's performance under various conditions. The results showed that sicegar tends to underestimate the true onset time as data dispersion increases. We then developed a parametric bootstrapping method to correct this bias, demonstrating that this fix can produce estimates that are closer to the real values. I produced this work alongside [Professor Jo Hardin](https://hardin47.netlify.app/). Find out more about this work [here](academicprojects/timeCourse.qmd).

:::{.callout-tip title="Extensions on GPR for Golf Modelling"}
I am currently working on publishing this summer's findings and am currently expanding on this paper by working on a topological interpretation of our work for my Senior excercise.
:::

Approximately every week for the last two years, I have participated in [tidytuesday](https://github.com/rfordatascience/tidytuesday), which is a weekly social data project with the opportunity to wrangle analyse and visualise new datasets everyweek. As of the creation of this website, I will start to upload my work [here](smallprojs/index.qmd).


### A little about me
When I'm not working on a problem set or on my thesis, I’m usually outside - golfing, doing something creative, or - lately - learning pickleball. I like trying new sports and staying active.

I am currently part of the **<span style="color: #275DAD; text-decoration: underline;   text-decoration-style: wavy;">Pomona</span>-<span style="color: #FE7F2D; text-decoration: underline;   text-decoration-style: wavy;">Pitzer</span>**'s Varsity Women's Golf team, hence this colourful theme!


### Tech & tools
Tools I feel comfortable with include `R`, `Python`, `Java`, `JavaScript`, and  `HTML` / `SCSS`. I use tidyverse-style workflows for data wrangling and visualization, and I’ve worked with HPC for large simulations.

---
I’m currently seeking **data science / analytics roles** that combine problem-solving, creativity, and impact - where I can keep learning and contribute to meaningful projects. If that sounds like a fit, let’s connect! ✨